select * from customer;
.... What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) 
from customer 
group by gender;
...q2.Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount 
from customer
where discount_applied='Yes' and purchase_amount>= (select avg(purchase_amount) from customer);
....q3.Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating::numeric),2) ....  here we changed double to integer
from customer 
group by item_purchased 
order by avg(review_rating) DESC LIMIT 5;
...q4  Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2)
from customer where shipping_type in ('Express','Standard')
group by shipping_type;
....q5 Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
count(customer_id), 
round(avg(purchase_amount),2),
round(sum(purchase_amount),2)
from customer 
group by subscription_status
order by avg(purchase_amount),sum(purchase_amount) DESC:
...q6.Which 5 products have the highest percentage of purchases with discounts applied? 
...Here we find sum of values where discount applied divide with count and to get the precentage into 100
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer   
group by item_purchased 
order by discount_rate DESC
limit 5;
...Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. Here we use CTE and case statements
with customer_type as (
select customer_id,previous_purchases,
case 
    when previous_purchases =1 then 'New'
    when previous_purchases between 2 and 10 then 'returning'
    else 'Loyal'
    END as customer_segment
from customer
)
select customer_segment,count(*)as "no of customers"
from customer_type 
group by customer_segment;
...q8.What are the top 3 most purchased products within each category? 
...here we need cTE and also window functions
with item_counts as (
select category,item_purchased,count(customer_id)as total_orders,
row_number()over (partition by category order by count(customer_id)DESC)as item_rank
from customer 
group by category,item_purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
...q9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) 
as repeated_buyers from customer
where previous_purchases>5 
group by subscription_status;
...q10.What is the revenue contribution of each age group? 
select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue DESC;







